import assert from 'node:assert/strict';
import test from 'node:test';
import {
  TorManager,
  buildTorrc,
  BUNDLED_TOR_SOCKS_PORT,
  BUNDLED_TOR_CONTROL_PORT,
} from './tor-manager.js';

function makeManager(socksPort?: number, controlPort?: number): TorManager {
  return new TorManager({
    dataDir: '/tmp/kiyeovo-tor-test',
    libp2pPort: 9001,
    torBinaryPath: '/nonexistent/tor',
    socksPort,
    controlPort,
  });
}

test('TorManager resolves to bundled defaults when ports are unset', () => {
  const manager = makeManager();
  assert.equal(manager.getSocksPort(), BUNDLED_TOR_SOCKS_PORT);
  assert.equal(manager.getControlPort(), BUNDLED_TOR_CONTROL_PORT);

  const state = manager.getState();
  assert.equal(state.socksPort, BUNDLED_TOR_SOCKS_PORT);
  assert.equal(state.controlPort, BUNDLED_TOR_CONTROL_PORT);
});

test('TorManager resolves to overridden ports when provided', () => {
  const manager = makeManager(19550, 19551);
  assert.equal(manager.getSocksPort(), 19550);
  assert.equal(manager.getControlPort(), 19551);

  const state = manager.getState();
  assert.equal(state.socksPort, 19550);
  assert.equal(state.controlPort, 19551);
});

test('buildTorrc embeds the default bundled ports byte-identically', () => {
  const torrc = buildTorrc(BUNDLED_TOR_SOCKS_PORT, BUNDLED_TOR_CONTROL_PORT, '/data/dir');
  assert.equal(
    torrc,
    `# Auto-generated by Kiyeovo
# Do not edit manually - changes will be overwritten

# SOCKS proxy for outgoing connections
SocksPort 9550

# Control port for dynamic hidden service creation
ControlPort 9551

# Data directory
DataDirectory /data/dir

# Performance tuning
CircuitBuildTimeout 30
NumEntryGuards 3

# Logging (to stdout, captured by Node.js)
Log notice stdout

# Disable some features we don't need
AvoidDiskWrites 1
`,
  );
});

test('buildTorrc reflects overridden ports', () => {
  const torrc = buildTorrc(19550, 19551, '/data/dir');
  assert.match(torrc, /^SocksPort 19550$/m);
  assert.match(torrc, /^ControlPort 19551$/m);
});
